/* Auto-generated by lcd_font_gen.py — 10 glyphs */
#ifndef LCD_DIGITS_DATA_H
#define LCD_DIGITS_DATA_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Compact glyph descriptor */
typedef struct {
    const uint8_t *data;   /* RLE compressed pixels */
    uint16_t      len;     /* RLE byte count        */
    uint16_t      width;   /* glyph pixel width     */
    uint16_t      height;  /* glyph pixel height    */
} DigitGlyph_t;

extern const DigitGlyph_t digit_glyphs[10];

#ifdef __cplusplus
}
#endif
#endif /* LCD_DIGITS_DATA_H */
