/* Auto-generated by lcd_font_gen.py */
#ifndef LCD_DIGITS_DATA_H
#define LCD_DIGITS_DATA_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const uint8_t digit_0_rle[1681];
extern const uint8_t digit_1_rle[1573];
extern const uint8_t digit_2_rle[1567];
extern const uint8_t digit_3_rle[1620];

/* Decode RLE and draw to LCD at (0,0) full-screen */
void LCD_DrawDigit(uint8_t digit);

#ifdef __cplusplus
}
#endif
#endif /* LCD_DIGITS_DATA_H */
