#!/usr/bin/env python3
"""
Times Roman 数字 0~9 小字模生成 & RLE 压缩
===========================================
使用 PIL 渲染 Times New Roman / Serif 字体，
为 STM32 + ILI9341 (240×320) 生成数字字模（1/8 屏大小）。
RLE 压缩：每字节 [7:6]=像素值(0~3), [5:0]=重复次数-1 (1~64)
"""

import argparse
import os
import subprocess
import sys
from typing import List, Tuple

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("需要 Pillow 库: pip install Pillow", file=sys.stderr)
    sys.exit(1)

# ============================================================
WIDTH = 240
HEIGHT = 320

# ============================================================
def find_times_font() -> str:
    """查找系统上可用的 Times/Serif 字体"""
    candidates = [
        "/usr/share/fonts/truetype/msttcorefonts/Times_New_Roman.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf",
        "/usr/share/fonts/truetype/liberation2/LiberationSerif-Regular.ttf",
        "/usr/share/fonts/liberation/LiberationSerif-Regular.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf",
        "/usr/share/fonts/TTF/DejaVuSerif.ttf",
        "/usr/share/fonts/truetype/noto/NotoSerif-Regular.ttf",
        "/usr/share/fonts/truetype/freefont/FreeSerif.ttf",
    ]
    for p in candidates:
        if os.path.isfile(p):
            return p
    try:
        r = subprocess.run(["fc-match", "-f", "%{file}", "Times New Roman"],
                           capture_output=True, text=True)
        path = r.stdout.strip()
        if path and os.path.isfile(path):
            return path
    except Exception:
        pass
    try:
        r = subprocess.run(["fc-match", "-f", "%{file}", "serif"],
                           capture_output=True, text=True)
        path = r.stdout.strip()
        if path and os.path.isfile(path):
            return path
    except Exception:
        pass
    return None


def render_digit(digit: int, font_path: str, scale_div: int = 8) -> Tuple[List[int], int, int]:
    """PIL 渲染单个数字字符，二分搜索最佳字号使其尽量充满 240x320，
    然后缩小到 1/scale_div。最终只返回字符紧凑区域。"""
    ch = str(digit)
    lo, hi, best = 10, 600, 10
    while lo <= hi:
        mid = (lo + hi) // 2
        try:
            f = ImageFont.truetype(font_path, mid)
        except Exception:
            hi = mid - 1
            continue
        b = f.getbbox(ch)
        fw, fh = b[2] - b[0], b[3] - b[1]
        if fw <= WIDTH * 0.92 and fh <= HEIGHT * 0.92:
            best = mid
            lo = mid + 1
        else:
            hi = mid - 1

    best = max(best // scale_div, 8)  # 字号缩小到 1/scale_div，最小 8px
    font = ImageFont.truetype(font_path, best)
    b = font.getbbox(ch)
    fw, fh = b[2] - b[0], b[3] - b[1]
    print(f"  字号={best}px, 字符尺寸={fw}×{fh}")

    # 只渲染字符本身区域（加少量 padding）
    pad = 2
    img_w = fw + pad * 2
    img_h = fh + pad * 2
    img = Image.new("1", (img_w, img_h), 0)  # 二值模式，无抗锯齿
    draw = ImageDraw.Draw(img)
    draw.text((pad - b[0], pad - b[1]), ch, fill=1, font=font)

    # 转像素列表：0=背景, 3=前景（二值图像只有 0/1）
    pixels = []
    for y in range(img_h):
        for x in range(img_w):
            pixels.append(3 if img.getpixel((x, y)) else 0)
    return pixels, img_w, img_h


# ============================================================
def rle_compress(pixels: List[int]) -> List[int]:
    """字节级 RLE: [7:6]=val(0~3), [5:0]=count-1(0~63 → run=1~64)"""
    out = []
    prev, run = pixels[0], 1
    for p in pixels[1:]:
        if p == prev and run < 64:
            run += 1
        else:
            out.append((prev << 6) | (run - 1))
            prev, run = p, 1
    out.append((prev << 6) | (run - 1))
    return out


def rle_decompress(data: List[int], total: int) -> List[int]:
    pixels = []
    for b in data:
        v = (b >> 6) & 0x3
        n = (b & 0x3F) + 1
        pixels.extend([v] * n)
    return pixels[:total]


def save_png(path: str, pixels: List[int], w: int, h: int):
    img = Image.new("1", (w, h))
    img.putdata([1 if p else 0 for p in pixels])
    img.save(path)
    print(f"  预览: {path}")


def format_c_array_hex8(name: str, data: List[int], per_line: int = 16) -> str:
    """将 RLE 字节列表格式化为 C uint8_t 数组"""
    lines = [f"/* Times Roman digit — RLE compressed, {len(data)} bytes */",
             f"const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        h = ", ".join(f"0x{b:02X}" for b in chunk)
        end = "," if i + per_line < len(data) else ""
        lines.append(f"    {h}{end}")
    lines.append("};")
    return "\n".join(lines)


def write_c_output(output_dir: str, glyphs: list):
    """将所有数字的紧凑字模数据写入 C 源文件
    glyphs: [(rle_data, width, height), ...] for digits 0~N-1
    """
    num = len(glyphs)
    c_path = os.path.join(output_dir, "lcd_digits_data.c")
    with open(c_path, "w", encoding="utf-8") as f:
        f.write(f"/* Auto-generated by lcd_font_gen.py — Times Roman digits 0~{num-1} */\n")
        f.write('#include "lcd_digits_data.h"\n\n')
        for d, (rle, w, h) in enumerate(glyphs):
            f.write(format_c_array_hex8(f"digit_{d}_rle", rle) + "\n\n")
        f.write(f"/* Glyph table: RLE data pointer + width + height */\n")
        f.write(f"const DigitGlyph_t digit_glyphs[{num}] = {{\n")
        for d, (rle, w, h) in enumerate(glyphs):
            f.write(f"    {{digit_{d}_rle, {len(rle)}, {w}, {h}}},\n")
        f.write("};\n")

    h_path = os.path.join(output_dir, "lcd_digits_data.h")
    with open(h_path, "w", encoding="utf-8") as f:
        f.write(f"""/* Auto-generated by lcd_font_gen.py — {num} glyphs */
#ifndef LCD_DIGITS_DATA_H
#define LCD_DIGITS_DATA_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* Compact glyph descriptor */
typedef struct {{
    const uint8_t *data;   /* RLE compressed pixels */
    uint16_t      len;     /* RLE byte count        */
    uint16_t      width;   /* glyph pixel width     */
    uint16_t      height;  /* glyph pixel height    */
}} DigitGlyph_t;

extern const DigitGlyph_t digit_glyphs[{num}];

#ifdef __cplusplus
}}
#endif
#endif /* LCD_DIGITS_DATA_H */
""")
    print(f"  C 源文件: {c_path}")
    print(f"  C 头文件: {h_path}")

# ============================================================
def main():
    p = argparse.ArgumentParser(description="Times Roman 数字 0~9 小字模生成")
    p.add_argument("--preview", action="store_true", help="保存 PNG 预览图")
    p.add_argument("-o", "--output", default="./", help="输出目录")
    p.add_argument("-f", "--font", default=None,
                   help="字体路径(默认自动查找 Times)")
    args = p.parse_args()

    fp = args.font or find_times_font()
    if not fp:
        print("错误: 未找到 Serif 字体，请用 -f 指定。"); sys.exit(1)
    print(f"字体: {fp}\n")

    total = WIDTH * HEIGHT
    raw4 = total // 4
    print(f"屏幕: {WIDTH}×{HEIGHT} = {total} 像素 | 字体缩放: 1/8 | 未压缩参考: {raw4} 字节\n")

    os.makedirs(args.output, exist_ok=True)
    t_rle = 0
    glyphs = []  # [(rle, w, h), ...]

    for d in range(10):
        print(f"--- 数字 {d} ---")
        px, w, h = render_digit(d, fp)
        px_total = w * h
        on = sum(1 for v in px if v)
        print(f"  点亮: {on}/{px_total} ({on/px_total*100:.1f}%)  区域: {w}×{h}")

        rle = rle_compress(px)
        sz = len(rle)
        t_rle += sz
        assert rle_decompress(rle, px_total) == px, f"数字{d} 解压验证失败"
        glyphs.append((rle, w, h))

        print(f"  RLE: {sz} 字节")
        if args.preview:
            save_png(os.path.join(args.output, f"times_{d}.png"), px, w, h)

    num_digits = 10
    print()
    print("=" * 50)
    print(f"总计 {num_digits} 数字: RLE {t_rle} 字节")
    print()

    # 输出 C 风格数组
    write_c_output(args.output, glyphs)


if __name__ == "__main__":
    main()
